# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rit-client}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tanner Donovan"]
  s.date = %q{2010-07-16}
  s.description = %q{A client that is used to consume Rit content (currently within a Rails applicaiton).}
  s.email = %q{ttdonovan@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md",
     "TODO"
  ]
  s.files = [
    "README.md",
     "Rakefile",
     "TODO",
     "VERSION",
     "lib/rit_client.rb",
     "lib/rit_client/configuration.rb",
     "lib/rit_client/errors.rb",
     "lib/rit_client/plate.rb",
     "lib/rit_client/rit_plate.rb"
  ]
  s.homepage = %q{http://github.com/ttdonovan/rit-client}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A gem that used to consume Rit content (currently within a Rails application).}
  s.test_files = [
    "spec/rit_client_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

